services:
    caddy:
        image: lucaslorentz/caddy-docker-proxy
        container_name: ${COMPOSE_PROJECT_NAME}-caddy
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        volumes:
            - caddy-data:/data
            - ./public:/var/www/html/public
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        depends_on:
            - php
            - phpmyadmin

    php:
        image: php:fpm
        container_name: ${COMPOSE_PROJECT_NAME}-php
        volumes:
            - ./:/var/www/html
        labels:
            caddy: localhost
            caddy.root: "* /var/www/html/public"
            caddy.php_fastcgi: "{{upstreams 9000}}"
            caddy.encode: zstd gzip
            caddy.file_server:
        restart: unless-stopped
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mariadb
        container_name: ${COMPOSE_PROJECT_NAME}-db
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MARIADB_USER: ${DB_USER:-php}
            MARIADB_PASSWORD: ${DB_PASSWORD:?}
            MARIADB_RANDOM_ROOT_PASSWORD: true
            MARIADB_DATABASE: ${DB_NAME:-app}
        restart: unless-stopped
        healthcheck:
            test:
                ["CMD", "/usr/local/bin/healthcheck.sh", "--innodb_initialized"]
            interval: 10s
            timeout: 5s
            retries: 5

    phpmyadmin:
        image: phpmyadmin
        container_name: ${COMPOSE_PROJECT_NAME}-phpmyadmin
        environment:
            PMA_HOST: db
            PMA_ABSOLUTE_URI: http://${DOMAIN:-localhost}/phpmyadmin/
        labels:
            caddy: ${DOMAIN:-localhost}
            caddy.redir: "/phpmyadmin /phpmyadmin/"
            caddy.handle_path: /phpmyadmin/*
            caddy.handle_path.reverse_proxy: "{{ upstreams 80 }}"
        depends_on:
            db:
                condition: service_healthy

volumes:
    caddy-data:
    db-data:
